---
title: "p8105_hw1_zf2212"
author: "Catherine"
date: "9/13/2018"
output: github_document
---
# Problem 1

```{r problem_1, warning = FALSE}
library(tidyverse)

## set seed to ensure reproducibility

set.seed(123)

## create a data frame

hw1_df = tibble(
  samp = runif(10, min = 0, max = 5),
  vec_logical = c(samp > 2),
  vec_char = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J"),
  vec_factor = factor(c(1, 0, 1, 1, 1, 0, 1, 1, 1, 0), level = c(1, 0), label = c("M", "F"))
)  

## numeric and logical vector works, character and factor vector doesn't

mean(hw1_df$samp)
mean(hw1_df$vec_logical)
mean(hw1_df$vec_char)
mean(hw1_df$vec_factor)

```

```{r convert_to_numeric, eval = FALSE}

vec_logical_num = as.numeric(hw1_df$vec_logical)
vec_char_num = as.numeric(hw1_df$vec_char)
vec_factor_num = as.numeric(hw1_df$vec_factor)

```

```{r more_convert, eval = FALSE}

vec_char_factor = as.factor(hw1_df$vec_char)
vec_char_factor_num = as.numeric(vec_char_factor)
vec_factor_char = as.character(hw1_df$vec_factor)
vec_factor_char_num = as.numeric(vec_factor_char)

```


